#!/bin/bash
#
# Handy script that cleans up the project folder, re-initializes the
# build system, compiles everything and runs the tests for us.

export DYLD_LIBRARY_PATH=`pwd`/tests
export LD_LIBRARY_PATH=`pwd`/tests
export PYTHONPATH=`pwd`/tests:`pwd`:$PYTHONPATH
SHOULD_CLEANUP="yes"
NON_VERBOSE="yes"

_yellow (){
    printf "\033[1;33m$1\033[0m"
}
_red (){
    printf "\033[1;31m$1\033[0m"
}

_broken () {
    _red 'dP                         dP                         \n'
    _red '88                         88                         \n'
    _red '88d888b. 88d888b. .d8888b. 88  .dP  .d8888b. 88d888b. \n'
    _red '88`  `88 88`  `88 88`  `88 88888"   88ooood8 88`  `88 \n'
    _red '88.  .88 88       88.  .88 88  `8b. 88.  ... 88    88 \n'
    _red '88Y8888` dP       `88888P` dP   `YP `88888P` dP    dP \n'
}
echo_if_nonverbose () {
    if [ "$NON_VERBOSE" == 'yes' ]; then
        echo $*
    fi;
}

logo () {
    _yellow '   d888888o.   8 8888         8 8888888888   8 8888888888   8 888888888o  `8.`8888.      ,8'"'"'\n'
    _yellow ' .`8888:'"'"' `88. 8 8888         8 8888         8 8888         8 8888    `88. `8.`8888.    ,8'"'"'\n'
    _yellow ' 8.`8888.   Y8 8 8888         8 8888         8 8888         8 8888     `88  `8.`8888.  ,8'"'"'\n'
    _yellow ' `8.`8888.     8 8888         8 8888         8 8888         8 8888     ,88   `8.`8888.,8'"'"'\n'
    _yellow '  `8.`8888.    8 8888         8 888888888888 8 888888888888 8 8888.   ,88'"'"'    `8.`88888'"'"'\n'
    _yellow '   `8.`8888.   8 8888         8 8888         8 8888         8 888888888P'"'"'      `8. 8888\n'
    _yellow '    `8.`8888.  8 8888         8 8888         8 8888         8 8888              `8 8888\n'
    _yellow '8b   `8.`8888. 8 8888         8 8888         8 8888         8 8888               8 8888\n'
    _yellow '`8b.  ;8.`8888 8 8888         8 8888         8 8888         8 8888               8 8888\n'
    _yellow ' `Y8888P ,88P'"'"' 8 888888888888 8 888888888888 8 888888888888 8 8888               8 8888\n'
    echo
    _red '8 8888        8     ,o888888o.     8 8888         8 8888         ,o888888o.  `8.`888b                 ,8'"'"'\n'
    _red '8 8888        8  . 8888     `88.   8 8888         8 8888      . 8888     `88. `8.`888b               ,8'"'"'\n'
    _red '8 8888        8 ,8 8888       `8b  8 8888         8 8888     ,8 8888       `8b `8.`888b             ,8'"'"'\n'
    _red '8 8888        8 88 8888        `8b 8 8888         8 8888     88 8888        `8b `8.`888b     .b    ,8'"'"'\n'
    _red '8 8888        8 88 8888         88 8 8888         8 8888     88 8888         88  `8.`888b    88b  ,8'"'"'\n'
    _red '8 8888        8 88 8888         88 8 8888         8 8888     88 8888         88   `8.`888b .`888b,8'"'"'\n'
    _red '8 8888888888888 88 8888        ,8P 8 8888         8 8888     88 8888        ,8P    `8.`888b8.`8888'"'"'\n'
    _red '8 8888        8 `8 8888       ,8P  8 8888         8 8888     `8 8888       ,8P      `8.`888`8.`88'"'"'\n'
    _red '8 8888        8  ` 8888     ,88'"'"'   8 8888         8 8888      ` 8888     ,88'"'"'        `8.`8'"'"' `8,`'"'"'\n'
    _red '8 8888        8     `8888888P'"'"'     8 888888888888 8 888888888888 `8888888P'"'"'           `8.`   `8'"'"'\n'
    echo
    echo
}

set-verbose () {
    export NON_VERBOSE="no"
}
cleanup () {
    # Cleanup
    > .gitignore
    git clean -qdf
    git checkout .gitignore
}

continuous-integration () {
    if [ ! -e `which virtualenvwrapper.sh` ]; then
        _broken
        exit 1
    fi;
    set-verbose
    cleanup
    compile
    source `which virtualenvwrapper.sh`
    mkvirtualenv --distribute --no-site-packages sleepy-hollow
    pip install -r requirements.pip
    tests
    exit $?
}

compile () {
    # Compilation
    cleanup > sleepy.log

    if [ "$NON_VERBOSE" == 'yes' ]; then
        printf "Preparing to compile..."
        (./autogen.sh 2>&1) 2>&1>> sleepy.log
    else
        ./autogen.sh
    fi;
    if [ "$?" != "0" ]; then
        echo
        cat sleepy.log
    else
        echo_if_nonverbose "OK"
    fi;
    if [ "$NON_VERBOSE" == 'yes' ]; then
        printf "Compiling sleepy hollow..."
        (make 2>&1) 2>&1>> sleepy.log
    else
        make
    fi;
    if [ "$?" != "0" ]; then
        echo
        cat sleepy.log
    else
        echo_if_nonverbose "OK"
    fi;
}

tests () {
    # Making it easier to run the tests
    if [ ! -e tests/*.so ]; then
        compile
    fi;
    cp -f lib/.libs/*.dylib tests
    cp -f python/.libs/*.so tests

    # Running the tests
    if [ "x$DISPLAY" == "x" ]; then
        xvfb-run --server-args="-screen 0 1024x768x24" nosetests --verbosity=2 -s tests
    else
        nosetests --verbosity=2 -s tests
    fi

    exit_status="$?"

    if [ "$SHOULD_CLEANUP" == "yes" ]; then
        # Cleaning up
        rm -f tests/*.{dylib,so}
    fi;
    exit $exit_status
}

show-help () {
    echo "USAGE: $0 [optional arguments]"
    echo
    echo "arguments:"
    echo "  --verbose/-v activates verbose mode"
    echo "      EXAMPLES:"
    echo "          ./sleepy --verbose test"
    echo "          ./sleepy -v compile"
    echo
    echo "  test/-t - runs the tests"
    echo "      EXAMPLES:"
    echo "          ./sleepy test"
    echo "          ./sleepy -t"
    echo
    echo "  sneeze/-s - clean up files generated by compilation or test steps"
    echo "      EXAMPLES:"
    echo "          ./sleepy sneeze"
    echo "          ./sleepy -s"
    echo
    echo "  nap/quick/-q - run the tests without cleaning up afterwards"
    echo "      EXAMPLES:"
    echo "          ./sleepy nap"
    echo "          ./sleepy quick"
    echo "          ./sleepy -s"
    echo
    echo "  compile/-c - compile sleepy hollow"
    echo "      EXAMPLES:"
    echo "          ./sleepy compile"
    echo "          ./sleepy -c"
    echo
    echo "  distribute/-d/dist - compile sleepy hollow and prepare it for a release"
    echo "      EXAMPLES:"
    echo "          ./sleepy dist"
    echo "          ./sleepy -d"
    echo "          ./sleepy distribute"
    echo
    echo "  server [port] - runs the builtin test server on the given port (defaults to 4000 if no port is provided)"
    echo "      EXAMPLES:"
    echo "          ./sleepy server 8080"
    echo "          ./sleepy server"
    echo
    echo "  ci/continuous-integration - run the tests aimed on continuous integration (i.e.: jenkins)"
    echo "      EXAMPLES:"
    echo "          ./sleepy ci"
    echo "          ./sleepy continuous-integration"
    echo

}

distribute () {
    # preparing for distribution
    compile
    mkdir -p dist
    printf "Preparing for distribution..."
    cp -f lib/.libs/*.dylib dist
    cp -f python/.libs/*.so dist
    echo "OK"
    echo
    echo "Sleepy hollow files are available under `pwd`/dist"
}

server () {
    python tests/server/__init__.py $1
}

all () {
    if [ "x$1" != "x" ];then
        printf "\033[1;31m"
        echo
        echo "Invalid argument: $*"
        echo
        printf "\033[0m"
        show-help
        exit 1
    fi;
    cleanup
    compile
    tests
}

if [ "$0" != "-bash" ]; then
    while [ "$1" ]; do
        case $1 in
            "-q" | "nap" | "quick")
                logo;
                export SHOULD_CLEANUP="no";
                tests;
                exit $?;;
            "-t" | "test") logo;tests;exit $?;;
            "-v" | "--verbose") set-verbose;;
            "-s" | "sneeze") cleanup;exit $?;;
            "-d" | "distribute" | "dist") logo;distribute;exit $?;;
            "server") logo;server $2;;
            "-c" | "compile") logo;compile ;exit $?;;
            "ci" | "continuous-integration") logo;continuous-integration ;exit $?;;
            "-h" | "help") logo;show-help;exit $?;;
            *) all $*; exit $?;;
        esac
        shift
    done
fi;
