#!/bin/bash
#
# Handy script that cleans up the project folder, re-initializes the
# build system, compiles everything and runs the tests for us.

if [ ! -e `which virtualenvwrapper.sh` ]; then
    show.broken
    color.yellow "PLEASE INSTALL VIRTUALENV!!!"
    exit 1
fi;
if [ "x$VIRTUALENVWRAPPER_HOOK_DIR" == "x" ]; then
    source `which virtualenvwrapper.sh`
fi;

export DYLD_LIBRARY_PATH=$(pwd)/sleepyhollow/.libs:$(pwd)/lib/.libs
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PYTHONPATH=$DYLD_LIBRARY_PATH:$(pwd)/sleepyhollow:$(pwd):$PYTHONPATH
WORKON_HOME=$HOME/.virtualenvs
VENVNAME=sleepy-hollow
SHOULD_CLEANUP="yes"
NON_VERBOSE="yes"
SERVER_NAME=sleepyhollowtestserver

_complete_commands () {
    local cur opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts="test clean compile shell saks banana test.load ci"
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    export COMPREPLY
    return 0

}

complete -F _complete_commands ./sleepy
complete -F _complete_commands sleepy

color.yellow (){
    printf "\033[1;33m$1\033[0m"
}
color.red (){
    printf "\033[1;31m$1\033[0m"
}
color.green (){
    printf "\033[1;32m$1\033[0m"
}
color.white (){
    printf "\033[1;37m$1\033[0m"
}
color.blue (){
    printf "\033[1;36m$1\033[0m"
}

should.recompile_sources () {
    echo "no"
}
show.broken () {
    color.red 'dP                         dP                         \n'
    color.red '88                         88                         \n'
    color.red '88d888b. 88d888b. .d8888b. 88  .dP  .d8888b. 88d888b. \n'
    color.red '88`  `88 88`  `88 88`  `88 88888"   88ooood8 88`  `88 \n'
    color.red '88.  .88 88       88.  .88 88  `8b. 88.  ... 88    88 \n'
    color.red '88Y8888` dP       `88888P` dP   `YP `88888P` dP    dP \n'
}
echo.nonverbose () {
    if [ "$NON_VERBOSE" == 'yes' ]; then
        echo $*
    fi;
}

show.logo () {
    color.yellow '   d888888o.   8 8888         8 8888888888   8 8888888888   8 888888888o  `8.`8888.      ,8'"'"'\n'
    color.yellow ' .`8888:'"'"' `88. 8 8888         8 8888         8 8888         8 8888    `88. `8.`8888.    ,8'"'"'\n'
    color.yellow ' 8.`8888.   Y8 8 8888         8 8888         8 8888         8 8888     `88  `8.`8888.  ,8'"'"'\n'
    color.yellow ' `8.`8888.     8 8888         8 8888         8 8888         8 8888     ,88   `8.`8888.,8'"'"'\n'
    color.yellow '  `8.`8888.    8 8888         8 888888888888 8 888888888888 8 8888.   ,88'"'"'    `8.`88888'"'"'\n'
    color.yellow '   `8.`8888.   8 8888         8 8888         8 8888         8 888888888P'"'"'      `8. 8888\n'
    color.yellow '    `8.`8888.  8 8888         8 8888         8 8888         8 8888              `8 8888\n'
    color.yellow '8b   `8.`8888. 8 8888         8 8888         8 8888         8 8888               8 8888\n'
    color.yellow '`8b.  ;8.`8888 8 8888         8 8888         8 8888         8 8888               8 8888\n'
    color.yellow ' `Y8888P ,88P'"'"' 8 888888888888 8 888888888888 8 888888888888 8 8888               8 8888\n'
    echo
    color.red '8 8888        8     ,o888888o.     8 8888         8 8888         ,o888888o.  `8.`888b                 ,8'"'"'\n'
    color.red '8 8888        8  . 8888     `88.   8 8888         8 8888      . 8888     `88. `8.`888b               ,8'"'"'\n'
    color.red '8 8888        8 ,8 8888       `8b  8 8888         8 8888     ,8 8888       `8b `8.`888b             ,8'"'"'\n'
    color.red '8 8888        8 88 8888        `8b 8 8888         8 8888     88 8888        `8b `8.`888b     .b    ,8'"'"'\n'
    color.red '8 8888        8 88 8888         88 8 8888         8 8888     88 8888         88  `8.`888b    88b  ,8'"'"'\n'
    color.red '8 8888        8 88 8888         88 8 8888         8 8888     88 8888         88   `8.`888b .`888b,8'"'"'\n'
    color.red '8 8888888888888 88 8888        ,8P 8 8888         8 8888     88 8888        ,8P    `8.`888b8.`8888'"'"'\n'
    color.red '8 8888        8 `8 8888       ,8P  8 8888         8 8888     `8 8888       ,8P      `8.`888`8.`88'"'"'\n'
    color.red '8 8888        8  ` 8888     ,88'"'"'   8 8888         8 8888      ` 8888     ,88'"'"'        `8.`8'"'"' `8,`'"'"'\n'
    color.red '8 8888        8     `8888888P'"'"'     8 888888888888 8 888888888888 `8888888P'"'"'           `8.`   `8'"'"'\n'
    echo
    echo
}

set-verbose () {
    export NON_VERBOSE="no"
}
cleanup () {
    color.blue "Cleaning up... "
    # Cleanup
    > .gitignore
    git clean -qdf
    git checkout .gitignore
    rm -f tests/*.{dylib,so} tests/sleepyhollow.py
    color.green "OK\n"
}

continuous-integration () {
    export NON_VERBOSE="yes"
    cleanup
    compile
    if [ ! -e $WORKON_HOME/$VENVNAME ]; then
        mkvirtualenv --distribute --no-site-packages $VENVNAME
    else
        if [ "x$VIRTUAL_ENV" == "x" ]; then
            workon $VENVNAME
        fi;
    fi;

    pip install -r requirements.pip 2>&1>>sleepy.log
    if [ "$?" != "0" ]; then
        echo
        cat sleepy.log
    fi;
    tests
    exit $?
}

compile () {
    # Compilation
    cleanup > sleepy.log

    if [ "$NON_VERBOSE" == 'yes' ]; then
        printf "Preparing to compile..."
        (./autogen.sh 2>&1) 2>&1>> sleepy.log
    else
        ./autogen.sh
    fi;
    if [ "$?" != "0" ]; then
        echo
        cat sleepy.log
    else
        echo.nonverbose "OK"
    fi;
    if [ "$NON_VERBOSE" == 'yes' ]; then
        printf "Compiling sleepy hollow..."
        (make 2>&1) 2>&1>> sleepy.log
    else
        make
    fi;
    if [ "$?" != "0" ]; then
        echo
        cat sleepy.log
    else
        echo.nonverbose "OK"
    fi;
}

server.start () {
    potential_port=$1
    if [ $((potential_port)) -gt 1024 ]; then
        export TEST_SERVER_PORT=$potential_port
        run_in_background="yes"
    else
        export TEST_SERVER_PORT=4000
        run_in_background="no"
    fi;
    color.blue "Running test server at port "
    color.green "$TEST_SERVER_PORT\n"

    if [ "x$VIRTUAL_ENV" == "x" ]; then
        if [ ! -e $WORKON_HOME/$VENVNAME ]; then
            mkvirtualenv --distribute --no-site-packages $VENVNAME
        else
            if [ "x$VIRTUAL_ENV" != "x" ]; then
                workon $VENVNAME
            fi;
        fi;
    fi;

    if [ $run_in_background == "yes" ]; then
        (python tests/server/__init__.py $TEST_SERVER_PORT 2>&1) 2>&1> server.log &
    else
        python tests/server/__init__.py $TEST_SERVER_PORT
    fi;
}
server.stop () {
    unset DYLD_LIBRARY_PATH
    unset LD_LIBRARY_PATH
    unset PYTHONPATH
    ps aux | egrep server/__init__.py | grep -v grep | awk '{ print $2 }' | xargs kill -9
    color.blue "Test server stopped\n"
}

tests () {
    server.start 5000
    # Making it easier to run the tests
    (make 2>&1) 2>&1 >>sleepy.log
    if [ "$?" != "0" ]; then
        compile
    fi;

    # Running the tests
    if [ "x$DISPLAY" == "x" ]; then
        xvfb-run --server-args="-screen 0 1024x768x24" nosetests --stop --verbosity=2 -s tests
    else
        nosetests --stop --verbosity=2 -s tests
    fi

    exit_status="$?"

    server.stop
    exit $exit_status
}

test.saks () {
    make 2>&1>/dev/null
    python tests/saks.py
}
test.banana () {
    make 2>&1>/dev/null
    python tests/banana.py
}
test.load () {
    (make 2>&1) 2>&1>/dev/null
    server.start 5000
    python tests/load.py
    server.stop
}
shell () {
    ipython
}

show-help () {
    echo "USAGE: $0 [optional arguments]"
    echo
    echo "arguments:"
    echo "  --verbose/-v activates verbose mode"
    echo "      EXAMPLES:"
    echo "          ./sleepy --verbose test"
    echo "          ./sleepy -v compile"
    echo
    echo "  test/-t - runs the tests"
    echo "      EXAMPLES:"
    echo "          ./sleepy test"
    echo "          ./sleepy -t"
    echo
    echo "  sneeze/clean/cleanup/-s - clean up files generated by compilation or test steps"
    echo "      EXAMPLES:"
    echo "          ./sleepy sneeze"
    echo "          ./sleepy -s"
    echo
    echo "  compile/-c - compile sleepy hollow"
    echo "      EXAMPLES:"
    echo "          ./sleepy compile"
    echo "          ./sleepy -c"
    echo
    echo "  shell - runs an interactive shell with sleepy hollow enabled"
    echo "      EXAMPLES:"
    echo "          ./sleepy shell"
    echo "  distribute/-d/dist - compile sleepy hollow and prepare it for a release"
    echo "      EXAMPLES:"
    echo "          ./sleepy dist"
    echo "          ./sleepy -d"
    echo "          ./sleepy distribute"
    echo
    echo "  server [port] - runs the builtin test server on the given port (defaults to 4000 if no port is provided)"
    echo "      EXAMPLES:"
    echo "          ./sleepy server 8080"
    echo "          ./sleepy server"
    echo
    echo "  ci/continuous-integration - run the tests aimed on continuous integration (i.e.: jenkins)"
    echo "      EXAMPLES:"
    echo "          ./sleepy ci"
    echo "          ./sleepy continuous-integration"
    echo

}

all () {
    if [ "x$1" == "x" ]; then
        cleanup && compile && tests
        exit $?
    fi;

    if [ "x$(echo $1 | egrep '^[0-9]{4,5}$')" == "x" ];then
        printf "\033[1;31m"
        echo
        echo "Invalid argument: $*"
        echo
        printf "\033[0m"
        show-help
        exit 1
    fi;
}

if [ "$0" != "-bash" ]; then
    while [ "$1" ]; do
        case $1 in
            "-t" | "test") show.logo;tests;exit $?;;
            "-v" | "--verbose") set-verbose;;
            "-s" | "sneeze" | "clean" | "cleanup") cleanup;;
            "shell") shell;;
            "server") show.logo;server.start $2;;
            "-c" | "compile") show.logo;compile ;exit $?;;
            "ci" | "continuous-integration") show.logo;continuous-integration ;exit $?;;
            "-h" | "help") show.logo;show-help;exit $?;;
            "saks") test.saks;exit $?;;
            "banana") test.banana;exit $?;;
            "test.load") test.load;exit $?;;
            *) all $*; exit $?;;
        esac
        shift
    done
fi;
